In [1]:
import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics


dir_data = 'data'
dir_output = 'output'

df = pd.read_csv(os.path.join(dir_data, 'herodata.csv'))
df = df.drop(['speed', 'sight', 'life_scale', 'life_regenScale', 'weapon_damageScale'], axis=1)
X = df.drop(['hero', 'role'], axis=1)
y = df[['role']]

In [3]:


# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


clf = RandomForestClassifier()
clf.fit(X_train, y_train)


# Predict the response for test dataset
y_pred = clf.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

# print results of predict
print('Actual - Prediction')
for yt, yp in zip(y_test.to_numpy(), y_pred):
    print(yt[0], '-', yp)

prediction_proba = clf.predict_proba(X_test)
print(prediction_proba)


Accuracy: 0.8333333333333334
Actual - Prediction
Ranged Assasin - Ranged Assasin
Healer - Healer
Melee Assasin - Melee Assasin
Ranged Assasin - Ranged Assasin
Bruiser - Bruiser
Melee Assasin - Ranged Assasin
Bruiser - Bruiser
Tank - Tank
Bruiser - Bruiser
Healer - Healer
Ranged Assasin - Ranged Assasin
Healer - Healer
Healer - Healer
Melee Assasin - Bruiser
Ranged Assasin - Ranged Assasin
Ranged Assasin - Ranged Assasin
Melee Assasin - Melee Assasin
Melee Assasin - Bruiser
[[0.09 0.35 0.03 0.44 0.08 0.01]
 [0.18 0.54 0.09 0.01 0.09 0.09]
 [0.14 0.18 0.31 0.29 0.02 0.06]
 [0.06 0.01 0.27 0.66 0.   0.  ]
 [0.49 0.01 0.01 0.03 0.   0.46]
 [0.16 0.02 0.33 0.46 0.02 0.01]
 [0.56 0.   0.02 0.   0.   0.42]
 [0.02 0.03 0.   0.04 0.03 0.88]
 [0.49 0.   0.02 0.08 0.02 0.39]
 [0.03 0.72 0.   0.07 0.13 0.05]
 [0.05 0.03 0.05 0.84 0.03 0.  ]
 [0.03 0.49 0.05 0.35 0.04 0.04]
 [0.   0.62 0.02 0.26 0.1  0.  ]
 [0.31 0.16 0.1  0.14 0.09 0.2 ]
 [0.   0.02 0.   0.98 0.   0.  ]
 [0.01 0.03 0.01 0.95 0.   

C:\Users\bxjxr\AppData\Local\Temp/ipykernel_4848/3926376897.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train, y_train)
