In [6]:
import os
import pandas as pd
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics


dir_data = 'data'
dir_output = 'output'

df = pd.read_csv(os.path.join(dir_data, 'herodata.csv'))
df = df.drop(['speed', 'sight', 'life_scale', 'life_regenScale', 'weapon_damageScale'], axis=1)
X = df.drop(['hero', 'role'], axis=1)
y = df[['role']]

In [7]:


# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


clf = RandomForestClassifier()
clf.fit(X_train, y_train)


# Predict the response for test dataset
y_pred = clf.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

# print results of predict
print('Actual - Prediction')
for yt, yp in zip(y_test.to_numpy(), y_pred):
    print(yt[0], '-', yp)

prediction_proba = clf.predict_proba(X_test)
print(prediction_proba)


Accuracy: 0.4444444444444444
Actual - Prediction
Bruiser - Ranged Assasin
Ranged Assasin - Ranged Assasin
Melee Assasin - Ranged Assasin
Melee Assasin - Bruiser
Bruiser - Tank
Healer - Healer
Tank - Bruiser
Melee Assasin - Bruiser
Healer - Healer
Ranged Assasin - Tank
Bruiser - Tank
Melee Assasin - Ranged Assasin
Ranged Assasin - Ranged Assasin
Ranged Assasin - Ranged Assasin
Support - Bruiser
Ranged Assasin - Ranged Assasin
Healer - Healer
Ranged Assasin - Ranged Assasin
[[0.25 0.04 0.24 0.43 0.   0.04]
 [0.   0.01 0.   0.99 0.   0.  ]
 [0.04 0.   0.3  0.66 0.   0.  ]
 [0.35 0.14 0.18 0.24 0.   0.09]
 [0.21 0.01 0.02 0.   0.   0.76]
 [0.   0.69 0.   0.21 0.1  0.  ]
 [0.63 0.04 0.01 0.   0.   0.32]
 [0.32 0.24 0.21 0.09 0.   0.14]
 [0.24 0.39 0.2  0.02 0.07 0.08]
 [0.31 0.15 0.   0.04 0.   0.5 ]
 [0.38 0.01 0.   0.02 0.   0.59]
 [0.12 0.21 0.17 0.47 0.   0.03]
 [0.   0.04 0.   0.96 0.   0.  ]
 [0.01 0.14 0.03 0.81 0.01 0.  ]
 [0.71 0.06 0.04 0.02 0.   0.17]
 [0.14 0.01 0.25 0.58 0.   0

C:\Users\bxjxr\AppData\Local\Temp/ipykernel_11996/2231131847.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train, y_train)


In [5]:
# save model to disk
pickle.dump(clf, open('rf_model.sav', 'wb'))